services:
  midiverse:
    build:
      context: ./
    restart: always
    container_name: midiverse
    volumes:
      - ./:/var/www/html
    networks:
      - local_dev
  nginx:
    build:
      context: ./nginx
    restart: always
    container_name: nginx
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - local_dev
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: midiverse
      MYSQL_USER: midiverse
      MYSQL_PASSWORD: midiverse
    ports:
      - "3306:3306"
    volumes:
      - /Users/egalan/persistent-storage:/var/lib/mysql
      - /Users/egalan/databases/:/databases
    networks:
      - local_dev
    restart: always
networks:
  local_dev:
    driver: bridge
